apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-services
  namespace: argocd
spec:
  description: Platform-managed service deployments
  sourceRepos:
    - "__PLATFORM_ENV_REPO_URL__"
  destinations:
    - namespace: platform-dev
      server: "__CLUSTER_API_SERVER__"
    - namespace: platform-staging
      server: "__CLUSTER_API_SERVER__"
    - namespace: platform-prod
      server: "__CLUSTER_API_SERVER__"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota

