apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: __ARGOCD_NAMESPACE__
spec:
  project: platform-services
  source:
    repoURL: __PLATFORM_ENV_REPO_URL__
    targetRevision: main
    path: environments
    directory:
      recurse: true
  destination:
    server: __CLUSTER_API_SERVER__
    namespace: __ARGOCD_NAMESPACE__
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

