apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders-api-staging
  namespace: __ARGOCD_NAMESPACE__
spec:
  project: platform-services
  sources:
    - repoURL: __PLATFORM_TEMPLATE_REPO_URL__
      targetRevision: main
      path: shared/helm/platform-service
      helm:
        valueFiles:
          - $values/environments/staging/values/orders-api.values.yaml
    - repoURL: __PLATFORM_ENV_REPO_URL__
      targetRevision: main
      ref: values
  destination:
    server: __CLUSTER_API_SERVER__
    namespace: platform-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

