# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", "~> 7.2"
gem "puma", "~> 6.4"
gem "pg"
gem "redis"
gem "bootsnap", require: false

group :development, :test do
  gem "rspec-rails"
  gem "rubocop"
end
